### ISSUE TITLE
 issue-templates voor niet snappen/NPM/REACT etc.

### ISSUE THREAD

**Issue by HjalmarSnoep** [TheHunterDog/Lessen#2]
issue-templates kijk maar bij mij https://github.com/HjalmarSnoep/SVG/issues
Als je op nieuw klikt krijg je eerste een drietal opties en dan krijg je een template met wat ik wil weten.

**Comment by TheHunterDog** [comment]
dat lijkt me handig maar ook weer onhandig omdat niet alles onder een onderwerp valt dus dan gaan mensen de vraag niet meer stellen
